// <auto-generated />
namespace Digital_Library.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class test101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test101));
        
        string IMigrationMetadata.Id
        {
            get { return "202104301043441_test101"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
